version: '3'
services:
  kafka1:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=101
      - KAFKA_CFG_ZOOKEEPER_CONNECT=10.138.39.126:2181,10.138.39.127:2181,10.138.39.128:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=test
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.138.39.126:9092
    volumes:
      - '/home/soa/kafka/kafka-persistence:/bitnami/kafka'
networks:
  outside:
    external: true
