version: '3'
services:
   kafdrop:
    image: 'obsidiandynamics/kafdrop:3.27.0'
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=10.138.39.126:9092
networks:
  outside:
    external: true