version: '3'
services:
  zookeeper2:
    image: 'bitnami/zookeeper:3.7.0'
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=10.138.39.126:2888:3888,0.0.0.0:2888:3888,10.138.39.128:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - '/home/soa/kafka/zookeeper-persistence:/bitnami/zookeeper'
networks:
  outside:
    external: true