version: '3'
services:
  zookeeper1:
    image: 'bitnami/zookeeper:3.7.0'
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,10.138.39.127:2888:3888,10.138.39.128:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=test
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=test
    volumes:
      - '/home/soa/kafka/zookeeper-persistence:/bitnami/zookeeper'
networks:
  outside:
    external: true