version: '3'
services:
  kafka:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=103
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=10.138.39.126:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.138.39.128:9092'
    volumes:
      - '/home/soa/kafka/kafka-persistence:/bitnami/kafka'
  kafdrop:
    image: 'obsidiandynamics/kafdrop:1.27.0'
    ports:
        - '9000:9000'
    environment:
        - KAFKA_BROKERCONNECT=10.138.39.126:9092
        - JVM_OPTS="-Xms32M -Xmx64M"
        - SERVER_SERVLET_CONTEXTPATH="/"
networks:
  outside:
    external: true
