version: '3'
services:
  kafka:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=102
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=10.138.39.126:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.138.39.127:9092'
    volumes:
      - '/home/soa/kafka/kafka-persistence:/bitnami/kafka'
networks:
  outside:
    external: true
